import {StyleSheet} from 'react-native';

export const Styles = (isDarkMode: boolean) =>
  StyleSheet.create({
    viewHome: {
      backgroundColor: isDarkMode ? '#0099E6' : '#00CEE6',
      height: '100%',
      marginStart: 5,
      marginEnd: 5,
      borderRadius: 8,
    },
    viewForm: {
      backgroundColor: isDarkMode ? '#0099E6' : '#00CEE6',
      height: '75%',
      marginStart: 14,
      marginEnd: 14,
      marginTop: 25,
      borderRadius: 8,
      padding: 18,
    },

    cardBackground: {
      backgroundColor: isDarkMode ? '#fff' : '#000',
      marginStart: 5,
      borderRadius: 8,
      marginEnd: 5,
      marginTop: 10,
      padding: 18,
      flexDirection: 'row',
      flex: 2,
    },
    cardText: {
      color: isDarkMode ? 'white' : 'black',
      fontSize: 18,
      fontFamily: 'Poppins-Regular',
      fontWeight: '700',
    },
    itemText: {
      color: isDarkMode ? 'black' : 'white',
      fontSize: 18,
      fontFamily: 'OpenSans-Regular',
      fontWeight: '700',
    },
    formText: {
      width: '75%',
      alignSelf: 'flex-start',
      fontSize: 18,
      color: isDarkMode ? 'white' : 'black',
      fontFamily: 'OpenSans-Regular',
    },
    cardTextContainer: {
      width: '75%',
      alignSelf: 'flex-start',
    },
    cardButton: {
      backgroundColor: isDarkMode ? 'black' : 'white',
      alignSelf: 'flex-end',
      padding: 13,
      borderRadius: 9,
    },
    formButton: {
      backgroundColor: isDarkMode ? 'black' : 'white',
      alignSelf: 'flex-end',
      padding: 13,
      borderRadius: 9,
    },
    imageHome: {
      width: '100%',
      height: '65%',
    },
    principalTextHome: {
      textAlign: 'center',
      color: isDarkMode ? 'white' : 'black',
      fontSize: 28,
      fontWeight: '700',
      fontFamily: 'Lato-Regular',
      textTransform: 'capitalize',
    },
    secondTextHome: {
      textAlign: 'center',
      color: isDarkMode ? 'white' : 'black',
      fontSize: 14,
      fontFamily: 'Poppins-Regular',
      fontWeight: '600',
    },
    gettingStartedButton: {
      alignSelf: 'center',
      color: isDarkMode ? 'white' : 'black',
      backgroundColor: isDarkMode ? 'white' : 'black',
      marginTop: 15,
      padding: 18,
      borderRadius: 10,
    },
    gettingStartedText: {
      color: isDarkMode ? 'black' : 'white',
      fontSize: 16,
      fontFamily: 'Lato-Regular',
    },
    cameraButton: {
      backgroundColor: isDarkMode ? 'white' : 'black',
      width: 38,
      borderRadius: 18,
      marginTop: -65,
      alignSelf: 'center',
    },
    deleteAllButton: {
      backgroundColor: isDarkMode ? 'red' : 'darkred',
      width: 150,
      alignSelf: 'flex-end',
      marginTop: 15,
      marginBottom: 10,
      padding: 12,
      marginEnd: 8,
      borderRadius: 15,
    },
    deleteAllText: {
      textAlign: 'center',
      color: 'white',
      fontSize: 16,
      fontFamily: 'Poppins-Regular',
      fontWeight: '600',
    },
    formInput: {
      borderBottomWidth: 2,
      borderBottomColor: isDarkMode ? 'white' : 'black',
      color: isDarkMode ? 'white' : 'black',
      fontSize: 18,
      fontFamily: 'Lato-Regular',
      marginBottom: 8,
    },
  });
